#!/bin/sh

# start compositor daemon
$HOME/.config/picom/launch.sh

# start desktop notification daemon
$HOME/.config/dunst/launch.sh

# start dwmbar daemon
$HOME/.config/dwm/statusbar

# disable screen saver / turn off monitor if inactived for 300 secs
xset s off
xset dpms 300 300 300
killall xss-lock
xss-lock $(which slock) &

# start network applet
pgrep -x nm-applet || nm-applet &

# start bluetooth applet
which blueman-applet && ! pgrep -x blueman-applet || blueman-applet &

# start screenshot tool
which flameshot && ! pgrep -x flameshot && flameshot &

# start input method
pgrep -x ibus-daemon || ibus-daemon -drx &

# restart wallpaper
nitrogen --restore

# start nextcloud
pgrep -x nextcloud || nextcloud &

